const works = [
  {
    id: 1,
    title: "Booking Trips",
    techs: ["HTML", "CSS", "JavaScript"],
    live: "https://alkhanbashi-tourism.firebaseapp.com/",
  },
  {
    id: 2,
    title: "STATED.",
    techs: ["HTML", "CSS", "JavaScript"],
    source: "https://github.com/mohammed-fandees/STATED",
    live: "https://stated.vercel.app/",
  },
  {
    id: 3,
    title: "Lonely",
    techs: ["HTML", "CSS", "JavaScript"],
    source: "https://github.com/mohammed-fandees/Lonely",
    live: "https://lonely-kappa.vercel.app/",
  },
  {
    id: 4,
    title: "Grayscale",
    techs: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    source: "https://github.com/mohammed-fandees/Porto",
    live: "https://porto-eta.vercel.app/",
  },
  {
    id: 5,
    title: "Portfolio Template",
    techs: ["HTML", "CSS", "JavaScript"],
    source: "https://github.com/mohammed-fandees/Portfo-Empeded",
    live: "https://portfo-empeded.vercel.app/#portfolio",
  },
  {
    id: 6,
    title: "Personal",
    techs: ["HTML", "CSS", "JavaScript"],
    source: "https://github.com/mohammed-fandees/Personal",
    live: "https://personal-lac-zeta.vercel.app/",
  },
  {
    id: 7,
    title: "Bondi",
    techs: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    source: "https://github.com/mohammed-fandees/Bondi",
    live: "https://bondi-three.vercel.app/",
  },
  {
    id: 8,
    title: "Client",
    techs: ["HTML", "CSS", "JavaScript"],
    source: "https://github.com/mohammed-fandees/client",
    live: "https://client-ten-livid.vercel.app/",
  },
  {
    id: 9,
    title: "Leon",
    techs: ["HTML", "CSS"],
    source: "https://github.com/mohammed-fandees/Leon-Template-One",
    live: "https://mohammed-fandees.github.io/Leon-Template-One/",
  },
  {
    id: 10,
    title: "Kasper",
    techs: ["HTML", "CSS"],
    source: "https://github.com/mohammed-fandees/Kasper",
    live: "https://mohammed-fandees.github.io/Kasper",
  },
  {
    id: 11,
    title: "Elzero",
    techs: ["HTML", "CSS"],
    source: "https://github.com/mohammed-fandees/Template-three-Elzero",
    live: "https://mohammed-fandees.github.io/Template-three-Elzero/",
  },
  {
    id: 12,
    title: "Wedgets",
    techs: ["HTML", "CSS"],
    source: "https://github.com/mohammed-fandees/Template-Four",
    live: "https://mohammed-fandees.github.io/Template-Four/",
  },
  {
    id: 13,
    title: "Huddle",
    techs: ["HTML", "CSS"],
    source: "https://github.com/mohammed-fandees/Huddle",
    live: "http://mohammed-fandees.github.io/Huddle/",
  },
  {
    id: 14,
    title: "Resume",
    techs: ["HTML", "CSS"],
    source: "https://github.com/mohammed-fandees/Portfolio-template",
    live: "https://portfolio-template-resume.vercel.app/",
  },
  {
    id: 15,
    title: "Melan",
    techs: ["HTML", "CSS"],
    source: "https://github.com/mohammed-fandees/melan-template",
    live: "https://melan-template.vercel.app/",
  },
  {
    id: 16,
    title: "Scroll - Day & Night",
    techs: ["HTML", "CSS"],
    source: "https://github.com/mohammed-fandees/day-night",
    live: "https://day-night-gilt.vercel.app/",
  },
  {
    id: 17,
    title: "Steps",
    techs: ["HTML", "CSS", "Javascript", "Bootstrap", "React"],
    source: "https://github.com/mohammed-fandees/Steps",
  },
  {
    id: 18,
    title: "Online Store",
    techs: ["HTML", "CSS", "Javascript", "Bootstrap", "React"],
    source: "https://github.com/mohammed-fandees/online-store",
  },
  {
    id: 19,
    title: "Cyporg React App",
    techs: ["HTML", "CSS", "Javascript", "Bootstrap", "React"],
    source: "https://github.com/mohammed-fandees/Cyporg-React-App",
  },
];
const title = {
  id: "portfolio",
  title: "my",
  customize: "portfolio",
  subtitle: "some of my ",
  subcustomize: `works (${works.length})`,
};

export { works, title };
